In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/process_classification_data.csv")

In [3]:
df.head()

,Unnamed: 0,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,0,1,-0.948880,-0.945448,0.274814,0.228446,-1.699001,0
1,1,0,-0.898767,-0.877932,-0.827242,0.621715,-1.651815,0
2,2,0,-0.948880,-1.012964,-0.133640,0.970039,-1.620357,0
3,3,0,-0.898767,-0.945448,-0.634575,-0.142350,-1.588900,0
4,4,0,-0.898767,-0.877932,-0.827242,-0.086169,-1.557442,0

In [4]:
df = df.iloc[0:,1:]

In [5]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,1,-0.948880,-0.945448,0.274814,0.228446,-1.699001,0
1,0,-0.898767,-0.877932,-0.827242,0.621715,-1.651815,0
2,0,-0.948880,-1.012964,-0.133640,0.970039,-1.620357,0
3,0,-0.898767,-0.945448,-0.634575,-0.142350,-1.588900,0
4,0,-0.898767,-0.877932,-0.827242,-0.086169,-1.557442,0

In [6]:
X = df.drop(columns=['Machine failure'],axis=1)

In [7]:
X.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
0,1,-0.948880,-0.945448,0.274814,0.228446,-1.699001
1,0,-0.898767,-0.877932,-0.827242,0.621715,-1.651815
2,0,-0.948880,-1.012964,-0.133640,0.970039,-1.620357
3,0,-0.898767,-0.945448,-0.634575,-0.142350,-1.588900
4,0,-0.898767,-0.877932,-0.827242,-0.086169,-1.557442

In [8]:
y = df['Machine failure']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Machine failure, dtype: int64

In [9]:
X.shape

(9535, 6)

In [10]:
y.shape

(9535,)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10,stratify=y)

In [13]:
print("X_train = ",X_train.shape)
print("X_test = ",X_test.shape)
print("y_train = ",y_train.shape)
print("y_test = ",y_test.shape)

X_train =  (7628, 6)
X_test =  (1907, 6)
y_train =  (7628,)
y_test =  (1907,)

In [14]:
print(y_train.value_counts())

Machine failure
0    7418
1     210
Name: count, dtype: int64

In [15]:
print(y_test.value_counts())

Machine failure
0    1854
1      53
Name: count, dtype: int64

In [16]:
X_train['Air temperature [K]']

4565    1.807356
5781    0.504408
3479    1.155882
8587   -1.399901
4442    1.657016
          ...
2057   -0.247293
9301   -0.748426
3414    0.905315
3609    1.205996
2982    0.053388
Name: Air temperature [K], Length: 7628, dtype: float64

In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [18]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [19]:
model.intercept_

array([-5.27133539])

In [20]:
model.coef_

array([[-0.33469577,  1.7850361 , -1.18594783, -0.39456696,  1.32231424,
         0.97852301]])

In [21]:
train_acc = model.score(X_train,y_train)

In [22]:
train_acc

0.9739119035133718

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
y_pred = model.predict(X_test)

In [25]:
accuracy = accuracy_score(y_test,y_pred)

In [26]:
accuracy

0.9737808075511274

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
cm = confusion_matrix(y_test,y_pred)

In [29]:
cm

array([[1851,    3],
       [  47,    6]])